'use client';

import React, { useState } from 'react';
import EmojiPicker, { Theme } from 'emoji-picker-react';

export default function SocialMediaHub({ tournament }: { tournament: any }) {
  const defaultTemplates = {
     instagram: `🏌️‍♂️ Spots are filling up fast for the ${tournament.name || 'Tournament'} at ${tournament.courseName || 'the course'}! ⛳\n\nWe have amazing sponsor opportunities still available and an incredible day of golf planned.\n\nSecure your foursome now! Link in bio. 🏆\n\n#GolfRegistration #CharityGolf #${(tournament.city || 'Local').replace(/[^a-zA-Z]/g,'')}Golf`,
     facebook: `It's time to hit the links! We are officially opening registration for the ${tournament.name} on ${new Date(tournament.dateStart || Date.now()).toLocaleDateString()}.\n\nThis event is hosted at ${tournament.courseName} and we are looking for local business partners to sponsor holes! Click the link below to get your team registered before we sell out.`,
     x: `🚨 Registration is LIVE for the ${tournament.name}!🚨\n\n📍 ${tournament.courseName}\n📅 ${new Date(tournament.dateStart || Date.now()).toLocaleDateString()}\n\nClick here to grab your team spot or become a hole sponsor before they are gone! 👇\nhttps://tourneylinks.com/t/${tournament.id}`
  };

  const [activeNetwork, setActiveNetwork] = useState<'instagram' | 'facebook' | 'x'>('instagram');
  const [isConnecting, setIsConnecting] = useState(false);
  const [showEmojiPicker, setShowEmojiPicker] = useState(false);
  const [mockConnected, setMockConnected] = useState<Record<string, boolean>>({
     instagram: false,
     facebook: false,
     x: false
  });
  
  const [customCaptions, setCustomCaptions] = useState(defaultTemplates);
  // Image Config Overrides
  const [customImages, setCustomImages] = useState<Record<string, string>>({});
  const [imageZooms, setImageZooms] = useState<Record<string, number>>({ instagram: 100, facebook: 100, x: 100 });
  const [imageYPos, setImageYPos] = useState<Record<string, number>>({ instagram: 50, facebook: 50, x: 50 });

  const handleConnect = (network: string) => {
     setIsConnecting(true);
     setTimeout(() => {
        window.location.href = `/api/oauth/social/connect?network=${network}&context=print-hub`;
     }, 600);
  };

  React.useEffect(() => {
     if (typeof window !== 'undefined') {
        const query = new URLSearchParams(window.location.search);
        if (query.get('social_success') === 'true') {
           const net = query.get('network') || 'instagram';
           setMockConnected(prev => ({ ...prev, [net]: true }));
           setActiveNetwork(net as 'instagram' | 'facebook' | 'x');
           window.history.replaceState({}, document.title, window.location.pathname);
        }
     }
  }, []);

  // Use the imagery populated from the tournament, fallback to gradient if not present
  const activeImage = customImages[activeNetwork] || tournament.heroImage;
  const activeZoom = imageZooms[activeNetwork] || 100;
  const activeYPos = imageYPos[activeNetwork] || 50;

  const heroStyle = activeImage 
    ? { 
        backgroundImage: `url(${activeImage})`, 
        backgroundSize: `${activeZoom}%`, 
        backgroundPosition: `center ${activeYPos}%`,
        backgroundRepeat: 'no-repeat'
      }
    : { background: 'linear-gradient(to bottom, var(--forest), #112211)' };

  // File Upload Handler
  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const url = URL.createObjectURL(e.target.files[0]);
      setCustomImages(prev => ({ ...prev, [activeNetwork]: url }));
    }
  };

  const profileName = mockConnected[activeNetwork] ? (tournament.courseName || tournament.name) : (activeNetwork === 'facebook' ? 'Your Page Name' : 'YourProfile');
  const profileHandle = mockConnected[activeNetwork] ? `@${(tournament.courseName || tournament.name).split(' ')[0].toLowerCase()}_golf` : '@yourhandle';
  const profileAvatarColor = mockConnected[activeNetwork] ? 'transparent' : '#ccc';
  const profileAvatarContent = mockConnected[activeNetwork] ? (
     <img src={`https://i.pravatar.cc/150?u=tourneylinks${tournament.id}`} alt="Profile" style={{ width: '100%', height: '100%', borderRadius: '50%', objectFit: 'cover' }} />
  ) : null;

  return (
    <div style={{ background: '#fff', color: '#111', padding: '2rem', borderRadius: '16px', marginBottom: '2rem', border: '1px solid #e5e7eb', boxShadow: '0 4px 15px rgba(0,0,0,0.03)' }}>
       <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
         <div>
           <h2 style={{ fontSize: '1.4rem', fontWeight: 700, marginBottom: '0.2rem', color: '#111' }}>Social Media & Marketing Engine</h2>
           <p style={{ color: '#666', fontSize: '0.85rem' }}>Autogenerated copy and graphics ready to post to your linked accounts.</p>
         </div>
       </div>

       <div style={{ display: 'grid', gridTemplateColumns: '200px 1fr 300px', gap: '1.5rem' }}>
          
          {/* Column 1: Navigation */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
             <button onClick={() => setActiveNetwork('instagram')} style={{ padding: '0.75rem 1rem', background: activeNetwork === 'instagram' ? 'linear-gradient(45deg, #f09433 0%, #e6683c 25%, #dc2743 50%, #cc2366 75%, #bc1888 100%)' : '#f9fafb', color: activeNetwork === 'instagram' ? '#fff' : '#111', fontWeight: 600, border: '1px solid #e5e7eb', borderRadius: '8px', cursor: 'pointer', textAlign: 'left', transition: '0.2s' }}>
                📸 Instagram
             </button>
             <button onClick={() => setActiveNetwork('facebook')} style={{ padding: '0.75rem 1rem', background: activeNetwork === 'facebook' ? '#1877F2' : '#f9fafb', color: activeNetwork === 'facebook' ? '#fff' : '#111', fontWeight: 600, border: '1px solid #e5e7eb', borderRadius: '8px', cursor: 'pointer', textAlign: 'left', transition: '0.2s' }}>
                📘 Facebook
             </button>
             <button onClick={() => setActiveNetwork('x')} style={{ padding: '0.75rem 1rem', background: activeNetwork === 'x' ? '#000' : '#f9fafb', color: activeNetwork === 'x' ? '#fff' : '#111', fontWeight: 600, border: '1px solid #e5e7eb', borderRadius: '8px', cursor: 'pointer', textAlign: 'left', transition: '0.2s' }}>
                𝕏 Twitter / X
             </button>
          </div>

          {/* Column 2: Editor & Auth */}
          <div style={{ background: '#f9fafb', borderRadius: '12px', padding: '1.5rem', border: '1px solid #e5e7eb', display: 'flex', flexDirection: 'column', position: 'relative' }}>
             <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: '0.5rem', position: 'relative' }}>
                <label style={{ color: 'var(--forest)', fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '1px', fontWeight: 700 }}>Edit Caption Live</label>
                <div style={{ display: 'flex', gap: '0.2rem', background: '#fff', border: '1px solid #e5e7eb', borderRadius: '6px', padding: '0.25rem 0.5rem', alignItems: 'center' }}>
                   {['⛳', '🏌️‍♂️', '🏆', '🚨', '📅'].map(emoji => (
                      <button 
                         key={emoji} 
                         onClick={() => setCustomCaptions(prev => ({ ...prev, [activeNetwork]: prev[activeNetwork] + emoji }))} 
                         style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: '1rem', padding: '0.2rem' }}
                         title={`Insert ${emoji}`}
                      >
                         {emoji}
                      </button>
                   ))}
                   <div style={{ width: '1px', height: '1.2rem', background: '#e5e7eb', margin: '0 0.3rem' }}></div>
                   <button onClick={() => setShowEmojiPicker(!showEmojiPicker)} style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: '1rem', padding: '0.2rem' }} title="Full Emoji Library">
                      ➕😊
                   </button>
                   {showEmojiPicker && (
                      <div style={{ position: 'absolute', top: '100%', right: 0, zIndex: 100, marginTop: '0.5rem', boxShadow: '0 10px 40px rgba(0,0,0,0.2)' }}>
                         <EmojiPicker 
                            theme={Theme.LIGHT} 
                            onEmojiClick={(emojiData) => {
                               setCustomCaptions(prev => ({ ...prev, [activeNetwork]: prev[activeNetwork] + emojiData.emoji }));
                               setShowEmojiPicker(false);
                            }} 
                         />
                      </div>
                   )}
                </div>
             </div>
             <textarea 
                value={customCaptions[activeNetwork]}
                onChange={(e) => setCustomCaptions({ ...customCaptions, [activeNetwork]: e.target.value })}
                placeholder="Type your social media caption here... Note: Social networks do not support bold/italics HTML, only plain text and emojis!"
                style={{ width: '100%', flex: 1, background: '#fff', color: '#111', border: '1px solid #d1d5db', borderRadius: '8px', padding: '1rem', fontFamily: 'inherit', lineHeight: 1.5, resize: 'none', marginBottom: '1.5rem', boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.02)' }}
             />
             
             {/* Image Overrides Controls */}
             <div style={{ background: '#fff', padding: '1rem', borderRadius: '8px', border: '1px solid #d1d5db', marginBottom: '1.5rem' }}>
                <label style={{ display: 'block', color: 'var(--forest)', fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '0.8rem', fontWeight: 700 }}>Image Framing Control</label>
                
                <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1rem' }}>
                   <div style={{ flex: 1 }}>
                     <label style={{ fontSize: '0.75rem', display: 'block', marginBottom: '0.2rem', color: '#444' }}>Zoom ({imageZooms[activeNetwork]}%)</label>
                     <input type="range" min="50" max="250" value={imageZooms[activeNetwork]} onChange={(e) => setImageZooms({ ...imageZooms, [activeNetwork]: parseInt(e.target.value) })} style={{ width: '100%' }} />
                   </div>
                   <div style={{ flex: 1 }}>
                     <label style={{ fontSize: '0.75rem', display: 'block', marginBottom: '0.2rem', color: '#444' }}>Nudge Y-Axis</label>
                     <input type="range" min="0" max="100" value={imageYPos[activeNetwork]} onChange={(e) => setImageYPos({ ...imageYPos, [activeNetwork]: parseInt(e.target.value) })} style={{ width: '100%' }} />
                   </div>
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                   <span style={{ fontSize: '0.75rem', color: '#666' }}>Upload custom graphic for this platform</span>
                   <label style={{ background: '#e5e7eb', color: '#111', padding: '0.4rem 0.8rem', borderRadius: '4px', fontSize: '0.8rem', cursor: 'pointer', fontWeight: 600 }}>
                      Choose File
                      <input type="file" accept="image/*" onChange={handleImageUpload} style={{ display: 'none' }} />
                   </label>
                </div>
             </div>

             {!mockConnected[activeNetwork] ? (
                 <button 
                   onClick={() => handleConnect(activeNetwork)}
                   disabled={isConnecting}
                   style={{ padding: '1rem', background: '#05120c', color: '#fff', fontWeight: 700, border: 'none', borderRadius: '8px', cursor: 'pointer' }}
                 >
                    {isConnecting ? 'Authenticating...' : `Connect ${activeNetwork.charAt(0).toUpperCase() + activeNetwork.slice(1)} Account`}
                 </button>
             ) : (
                 <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', justifyContent: 'center', color: '#059669', fontSize: '0.8rem', fontWeight: 600, background: '#ecfdf5', padding: '0.5rem', borderRadius: '6px', border: '1px solid #d1fae5' }}>
                       🟢 Successfully connected to {activeNetwork.charAt(0).toUpperCase() + activeNetwork.slice(1)}
                    </div>
                    <button onClick={() => alert('This will trigger the Live API flow once production OAuth keys are installed.')} style={{ padding: '1rem', background: 'linear-gradient(45deg, var(--gold), #e6c86e)', color: '#000', fontWeight: 800, border: 'none', borderRadius: '8px', cursor: 'pointer', boxShadow: '0 4px 10px rgba(0,0,0,0.1)' }}>
                       Post Live to {activeNetwork.charAt(0).toUpperCase() + activeNetwork.slice(1)} Now 🚀
                    </button>
                 </div>
             )}
          </div>

          {/* Column 3: Live Visual Preview */}
          <div style={{ background: activeNetwork === 'x' ? '#000' : '#fff', borderRadius: '12px', border: activeNetwork === 'x' ? '1px solid #333' : '1px solid #e5e7eb', overflow: 'hidden', boxShadow: '0 4px 20px rgba(0,0,0,0.08)', display: 'flex', flexDirection: 'column' }}>
              
              {/* Instagram Mock */}
              {activeNetwork === 'instagram' && (
                 <>
                    <div style={{ padding: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem', borderBottom: '1px solid #efefef', color: '#000' }}>
                       <div style={{ width: 32, height: 32, borderRadius: '50%', background: profileAvatarColor, color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold' }}>{profileAvatarContent}</div>
                       <div style={{ fontWeight: 600, fontSize: '0.85rem' }}>{profileName}</div>
                    </div>
                    <div style={{ height: '250px', ...heroStyle, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', textAlign: 'center', padding: '1rem' }}>
                       {!activeImage && <h2 style={{ fontFamily: 'serif', fontSize: '1.5rem', color: 'var(--gold)' }}>{tournament.name}</h2>}
                    </div>
                    <div style={{ padding: '1rem', color: '#000', fontSize: '0.8rem', flex: 1, overflowY: 'auto' }}>
                       <div style={{ fontWeight: 600, marginBottom: '0.2rem' }}>{profileName}</div>
                       <div style={{ whiteSpace: 'pre-wrap' }}>{customCaptions.instagram}</div>
                    </div>
                 </>
              )}

              {/* Facebook Mock */}
              {activeNetwork === 'facebook' && (
                 <>
                    <div style={{ padding: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem', color: '#050505' }}>
                       <div style={{ width: 36, height: 36, borderRadius: '50%', background: profileAvatarColor, color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold' }}>{profileAvatarContent}</div>
                       <div>
                          <div style={{ fontWeight: 600, fontSize: '0.9rem' }}>{profileName}</div>
                          <div style={{ fontSize: '0.75rem', color: '#65676B' }}>Just now · 🌎</div>
                       </div>
                    </div>
                    <div style={{ padding: '0 1rem 1rem 1rem', color: '#050505', fontSize: '0.9rem', whiteSpace: 'pre-wrap' }}>
                       {customCaptions.facebook}
                    </div>
                    <div style={{ height: '180px', ...heroStyle, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '1rem' }}>
                       {!activeImage && <div style={{ color: 'var(--forest)', fontWeight: 700, fontSize: '1.2rem', textAlign: 'center' }}>{tournament.name}</div>}
                    </div>
                 </>
              )}

              {/* X Mock */}
              {activeNetwork === 'x' && (
                 <>
                    <div style={{ padding: '1rem', display: 'flex', gap: '0.75rem', color: '#fff' }}>
                       <div style={{ width: 40, height: 40, borderRadius: '50%', background: mockConnected[activeNetwork] ? 'var(--forest)' : '#333', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold', flexShrink: 0 }}>{profileAvatarContent}</div>
                       <div style={{ flex: 1, minWidth: 0 }}>
                          <div style={{ display: 'flex', gap: '0.3rem', alignItems: 'center', flexWrap: 'wrap' }}>
                             <div style={{ fontWeight: 700, fontSize: '0.95rem' }}>{profileName}</div>
                             <div style={{ color: '#71767b', fontSize: '0.9rem' }}>{profileHandle} · 1m</div>
                          </div>
                          <div style={{ marginTop: '0.2rem', fontSize: '0.95rem', whiteSpace: 'pre-wrap', wordWrap: 'break-word', lineHeight: 1.4 }}>
                             {customCaptions.x}
                          </div>
                          <div style={{ marginTop: '0.75rem', borderRadius: '16px', overflow: 'hidden', border: '1px solid #2f3336' }}>
                             <div style={{ height: '120px', ...heroStyle }}></div>
                             <div style={{ padding: '0.5rem 0.75rem', background: '#000', borderTop: '1px solid #2f3336' }}>
                                <div style={{ fontSize: '0.8rem', color: '#71767b' }}>tourneylinks.com</div>
                                <div style={{ fontSize: '0.9rem', color: '#fff', marginTop: '0.1rem', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>Register for {tournament.name}</div>
                             </div>
                          </div>
                       </div>
                    </div>
                 </>
              )}
          </div>
       </div>
    </div>
  );
}
