'use client';

import React, { useState } from 'react';

export default function SocialMediaHub({ tournament }: { tournament: any }) {
  const [activeNetwork, setActiveNetwork] = useState<'instagram' | 'facebook' | 'x'>('instagram');
  const [isConnecting, setIsConnecting] = useState(false);
  const [mockConnected, setMockConnected] = useState<Record<string, boolean>>({
     instagram: false,
     facebook: false,
     x: false
  });

  const handleConnect = (network: string) => {
     setIsConnecting(true);
     // Simulate an OAuth redirect workflow
     setTimeout(() => {
        window.location.href = `/api/oauth/social/connect?network=${network}&context=print-hub`;
     }, 600);
  };

  // Mock checking URL parameters to see if we just came back from a successful OAuth
  React.useEffect(() => {
     if (typeof window !== 'undefined') {
        const query = new URLSearchParams(window.location.search);
        if (query.get('social_success') === 'true') {
           const net = query.get('network') || 'instagram';
           setMockConnected(prev => ({ ...prev, [net]: true }));
           setActiveNetwork(net as 'instagram' | 'facebook' | 'x');
           
           // Clean up URL
           window.history.replaceState({}, document.title, window.location.pathname);
        }
     }
  }, []);

  const templates = {
     instagram: {
        caption: `🏌️‍♂️ Spots are filling up fast for the ${tournament.name || 'Tournament'} at ${tournament.courseName || 'the course'}! ⛳\n\nWe have amazing sponsor opportunities still available and an incredible day of golf planned.\n\nSecure your foursome now! Link in bio. 🏆\n\n#GolfRegistration #CharityGolf #${(tournament.city || 'Local').replace(/[^a-zA-Z]/g,'')}Golf`,
        imageLabel: 'Sponsorship Flyer & Hero Image Carousel'
     },
     facebook: {
        caption: `It's time to hit the links! We are officially opening registration for the ${tournament.name} on ${new Date(tournament.dateStart || Date.now()).toLocaleDateString()}.\n\nThis event is hosted at ${tournament.courseName} and we are looking for local business partners to sponsor holes! Click the link below to get your team registered before we sell out.`,
        imageLabel: 'Event Hero Graphic + Registration Link Card'
     },
     x: {
        caption: `🚨 Registration is LIVE for the ${tournament.name}!🚨\n\n📍 ${tournament.courseName}\n📅 ${new Date(tournament.dateStart || Date.now()).toLocaleDateString()}\n\nClick here to grab your team spot or become a hole sponsor before they are gone! 👇\nhttps://tourneylinks.com/t/${tournament.id}`,
        imageLabel: 'Link Preview Card'
     }
  };

  return (
    <div style={{ background: '#111', color: '#fff', padding: '2rem', borderRadius: '16px', marginBottom: '2rem', border: '1px solid #333' }}>
       <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
         <div>
           <h2 style={{ fontSize: '1.4rem', fontWeight: 700, marginBottom: '0.2rem' }}>Social Media & Marketing Engine</h2>
           <p style={{ color: '#aaa', fontSize: '0.85rem' }}>Autogenerated copy and graphics ready to post to your linked accounts.</p>
         </div>
       </div>

       <div style={{ display: 'flex', gap: '1.5rem' }}>
          
          {/* Navigation */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', width: '200px' }}>
             <button onClick={() => setActiveNetwork('instagram')} style={{ padding: '0.75rem 1rem', background: activeNetwork === 'instagram' ? 'var(--gold)' : '#222', color: activeNetwork === 'instagram' ? '#000' : '#fff', fontWeight: 600, border: 'none', borderRadius: '8px', cursor: 'pointer', textAlign: 'left', transition: '0.2s' }}>
                📸 Instagram
             </button>
             <button onClick={() => setActiveNetwork('facebook')} style={{ padding: '0.75rem 1rem', background: activeNetwork === 'facebook' ? '#1877F2' : '#222', color: '#fff', fontWeight: 600, border: 'none', borderRadius: '8px', cursor: 'pointer', textAlign: 'left', transition: '0.2s' }}>
                📘 Facebook
             </button>
             <button onClick={() => setActiveNetwork('x')} style={{ padding: '0.75rem 1rem', background: activeNetwork === 'x' ? '#fff' : '#222', color: activeNetwork === 'x' ? '#000' : '#fff', fontWeight: 600, border: 'none', borderRadius: '8px', cursor: 'pointer', textAlign: 'left', transition: '0.2s' }}>
                𝕏 Twitter / X
             </button>
          </div>

          {/* Editor & Preview */}
          <div style={{ flex: 1, background: '#1c1c1c', borderRadius: '12px', padding: '1.5rem', border: '1px solid #333' }}>
             
             {!mockConnected[activeNetwork] ? (
                <div style={{ textAlign: 'center', padding: '3rem 1rem' }}>
                   <div style={{ fontSize: '2.5rem', marginBottom: '1rem' }}>🔗</div>
                   <h3 style={{ marginBottom: '0.5rem', fontWeight: 600 }}>Connect Your {activeNetwork.charAt(0).toUpperCase() + activeNetwork.slice(1)} Account</h3>
                   <p style={{ color: '#aaa', fontSize: '0.85rem', marginBottom: '1.5rem', maxWidth: '400px', margin: '0 auto 1.5rem auto' }}>
                      Securely authenticate TourneyLinks to allow 1-click publishing of your marketing flyers directly to your feed.
                   </p>
                   <button 
                     onClick={() => handleConnect(activeNetwork)}
                     disabled={isConnecting}
                     style={{ padding: '0.75rem 2rem', background: '#fff', color: '#000', fontWeight: 700, border: 'none', borderRadius: '8px', cursor: 'pointer' }}
                   >
                      {isConnecting ? 'Authenticating with OAuth...' : 'Connect Account'}
                   </button>
                </div>
             ) : (
                <div style={{ display: 'flex', gap: '1.5rem' }}>
                   <div style={{ flex: 1 }}>
                     <label style={{ display: 'block', color: 'var(--gold)', fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '0.5rem', fontWeight: 700 }}>Generated Caption</label>
                     <textarea 
                        defaultValue={templates[activeNetwork].caption}
                        style={{ width: '100%', height: '150px', background: '#2a2a2a', color: '#fff', border: '1px solid #444', borderRadius: '8px', padding: '1rem', fontFamily: 'inherit', lineHeight: 1.5, resize: 'none' }}
                     />
                     <button style={{ marginTop: '1rem', padding: '0.75rem 1rem', width: '100%', background: 'linear-gradient(45deg, var(--gold), #e6c86e)', color: '#000', fontWeight: 800, border: 'none', borderRadius: '8px', cursor: 'pointer' }}>
                        Post Live to {activeNetwork.charAt(0).toUpperCase() + activeNetwork.slice(1)} Now 🚀
                     </button>
                   </div>
                   <div style={{ width: '250px', background: '#000', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px dashed #444', padding: '1rem', textAlign: 'center' }}>
                      <div>
                         <p style={{ fontSize: '0.8rem', color: '#aaa', marginBottom: '0.5rem' }}>Attached Media</p>
                         <p style={{ fontWeight: 600, color: 'var(--gold)' }}>{templates[activeNetwork].imageLabel}</p>
                         <p style={{ fontSize: '0.7rem', color: '#666', marginTop: '1rem' }}>(Pulls automatically from your Print Station flyer settings)</p>
                      </div>
                   </div>
                </div>
             )}
          </div>
       </div>
    </div>
  );
}
