import { NextRequest, NextResponse } from 'next/server';
import { db, registrations } from '@/lib/db';
import { eq } from 'drizzle-orm';

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params;
    const tournamentId = parseInt(id);
    if (isNaN(tournamentId)) return NextResponse.json({ error: 'Invalid config' }, { status: 400 });

    const players = await db.select().from(registrations).where(eq(registrations.tournamentId, tournamentId));
    
    if (players.length === 0) {
        // Genuinely insert the mock teams so Postgres Foreign Keys don't block the Live Scoring Demo POSTs!
        const demoTeams = [
            { tournamentId, name: 'Team Woods', email: 'woods@test.com', handicap: -7, teamGroupId: 101 },
            { tournamentId, name: 'Team McIlroy', email: 'mcilroy@test.com', handicap: -5, teamGroupId: 102 },
            { tournamentId, name: 'Team Scheffler', email: 'scheffler@test.com', handicap: -8, teamGroupId: 103 },
            { tournamentId, name: 'Team Rahm', email: 'rahm@test.com', handicap: -6, teamGroupId: 104 },
            { tournamentId, name: 'Team Smith', email: 'smith@test.com', handicap: -4, teamGroupId: 105 },
            { tournamentId, name: 'Team Johnson', email: 'johnson@test.com', handicap: -5, teamGroupId: 106 }
        ];
        
        // Use returning() to get the actual DB IDs generated by Postgres Serial
        const insertedTeams = await db.insert(registrations).values(demoTeams).returning();
        
        return NextResponse.json(insertedTeams.map(t => ({
             id: t.id,
             firstName: t.name, // The TV and Mobile apps currently look for 'firstName' 
             lastName: '',
             handicapIndex: t.handicap ? t.handicap.toString() : ''
        })));
    }

    // Map existing rows to standard JSON payload, dynamically appending 'Team' to simulate Scrambles
    return NextResponse.json(players.map(p => {
        const lastName = p.name.split(' ').pop();
        const teamName = p.name.toLowerCase().includes('team') ? p.name : `Team ${lastName}`;

        return {
            id: p.id,
            firstName: teamName,
            lastName: '',
            handicapIndex: p.handicap ? p.handicap.toString() : ''
        };
    }));
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
